=== Marklogic-retired/marklogic-data-hub/specs/models/Flow.schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "$id": "http://marklogic.com/data-hub/Flow.schema.json",
  "title": "Flow",
  "type": "object",
  "description": "A Data Hub flow containing zero or many steps",
  "properties": {
    "name": {
      "type": "string",
      "description": "Unique name for the flow"
    },
    "description": {
      "type": "string",
      "description": "Optional description of the flow"
    },
    "batchSize": {
      "type": "number",
      "description": "Default batch size for every step"
    },
    "threadCount": {
      "type": "number",
      "description": "Default thread count for every step"
    },
    "stopOnError": {
      "type": "boolean",
      "description": "If true and an error is encountered, the flow run ends, the rest of the source data is ignored, and the remaining steps are not performed. Information about the failure is logged in the job document. Default is false."
    },
    "options": {
      "type": "object",
      "description": "Default options for every step. Not yet known what is typically defined here; may be rarely used",
      "properties": {
      }
    },
    "version": {
      "type": "number",
      "description": "Does not appear to be used for anything"
    },
    "steps": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": {
        "^[0-9]+$": {
          "oneOf": [
            {
              "properties": {
                "name": {
                  "type": "string",
                  "description": "Name of step, though the 'step number' is how a step is referred to when running a flow"
                },
                "description": {
                  "type": "string",
                  "description": "Optional description of the step"
                },
                "stepDefinitionName": {
                  "type": "string"
                },
                "stepDefinitionType": {
                  "type": "string"
                },
                "batchSize": {
                  "type": "number",
                  "description": "If set, overrides the batchSize defined at the flow level and in the step definition"
                },
                "threadCount": {
                  "type": "number",
                  "description": "If set, overrides the threadCount defined at the flow level and in the step definition"
                },
                "customHook": {
                  "type": "object",
                  "$ref": "./CustomHook.schema.json"
                },
                "processors": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "path": {
                        "type": "string",
                        "description": "Path to a module in the modules database that will be invoked via xdmp.invoke"
                      },
                      "when": {
                        "type": "string",
                        "description": "When the processor should be invoked. Only 'beforeContentPersisted' is supported."
                      },
                      "vars": {
                        "type": "object",
                        "description": "Any properties defined in this object are passed to the invoked module"
                      }
                    }
                  }
                },
                "fileLocations": {
                  "type": "object",
                  "description": "Applicable only to ingestion steps run via Gradle or QuickStart; not applicable when using MLCP",
                  "properties": {
                    "inputFilePath": {
                      "type": "string"
                    },
                    "inputFileType": {
                      "type": "string"
                    },
                    "outputURIReplacement": {
                      "type": "string"
                    },
                    "outputURIPrefix": {
                      "type": "string"
                    },
                    "separator": {
                      "type": "string"
                    }
                  }
                },
                "options": {
                  "type": "object",
                  "properties": {
                    "sourceQuery": {
                      "type": "string",
                      "description": "Defines the items to be processed by the step; must be a cts.query or cts.uris statement if sourceQueryIsScript is false"
                    },
                    "sourceQueryIsScript": {
                      "type": "boolean",
                      "description": "Added in 5.3.0; if true, then sourceQuery can be any JavaScript statement that can be passed into xdmp.eval"
                    },
                    "constrainSourceQueryToJob": {
                      "type": "boolean",
                      "description": "If true, the query is applied to the documents that were created or modified in the same job that executes the step"
                    },
                    "excludeAlreadyProcessed": {
                      "type": "boolean",
                      "description": "Added in 5.4.0; if true, then any items returned by the sourceQuery will be excluded from processing if a Batch document indicates that the item was processed by this step already"
                    },
                    "provenanceGranularityLevel": {
                      "type": "string",
                      "description": "The granularity of the provenance tracking information: coarse (default) to store document-level provenance information only, fine to store document-level and property-level provenance information, or off to disable provenance tracking in future job runs. Applies only to mapping, matching, merging, mastering, and custom steps."
                    },
                    "stepUpdate": {
                      "type": "boolean",
                      "description": "If true, custom modules can make changes directly to records in the database"
                    },
                    "acceptsBatch": {
                      "type": "boolean",
                      "description": "If true, the step module is invoked once with all records in the batch passed to it"
                    },
                    "collections": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    },
                    "additionalCollections": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    },
                    "permissions": {
                      "type": "string",
                      "description": "Comma-delimited string of role,capability,role,capability,etc"
                    },
                    "outputFormat": {
                      "type": "string"
                    },
                    "sourceDatabase": {
                      "type": "string"
                    },
                    "targetDatabase": {
                      "type": "string"
                    },
                    "targetEntity": {
                      "type": "string",
                      "description": "Name of the entity type associated with the output of the step"
                    },
                    "validateEntity": {
                      "type": "boolean",
                      "description": "Applicable to mapping steps only"
                    },
                    "headers": {
                      "type": "object",
                      "description": "Any properties in this object will be copied into the headers of each document processed by the step"
                    },
                    "mapping": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string",
                          "description": "The name of your mapping that is defined in your-project-root/mappings/your-mapping-name/mapping.version.json"
                        },
                        "version": {
                          "type": "string",
                          "description": "The version of the mapping to use, as defined in the mapping artifact"
                        }
                      }
                    },
                    "matchOptions": {
                      "type": "object"
                    },
                    "mergeOptions": {
                      "type": "object"
                    }
                  }
                }
              }
            },
            {
              "properties": {
                "stepId": {
                  "type": "string",
                  "description": "stepID links to an external step document"
                }
              },
              "required": [
                "stepId"
              ]
            }
          ],
          "type": "object"
        }
      }
    }
  },
  "required": [
    "name"
  ]
}

=== Marklogic-retired/marklogic-data-hub/examples/dh-5-example/flows/ingestion_mapping_mastering-flow.flow.json
{
  "name": "ingestion_mapping_mastering-flow",
  "description": "This is the default flow containing all of the default steps",
  "batchSize": 100,
  "threadCount": 4,
  "options": {
    "sourceQuery": null
  },
  "steps": {
    "1": {
      "name": "ingest-step-json",
      "description": "ingests json docs to data-hub-STAGING",
      "stepDefinitionName": "default-ingestion",
      "stepDefinitionType": "INGESTION",
      "options": {
        "sourceQuery": null,
        "collections": [
          "mastering-flow-ingest-json"
        ],
        "permissions": "rest-reader,read,rest-writer,update",
        "outputFormat": "json",
        "targetDatabase": "data-hub-STAGING"
      },
      "customHook": {},
      "retryLimit": 0,
      "batchSize": 100,
      "threadCount": 4,
      "fileLocations": {
        "inputFilePath": "mastering-input",
        "inputFileType": "json",
        "outputURIReplacement": ".*input*.,'/mastering-flow/json/'"
      }
    },
    "2": {
      "name": "mapping-step-json",
      "description": "maps and harmonizes docs to data-hub-FINAL",
      "stepDefinitionName": "default-mapping",
      "stepDefinitionType": "MAPPING",
      "options": {
        "sourceQuery": "cts.collectionQuery('mastering-flow-ingest-json')",
        "mapping": {
          "name": "OrderMappingJson",
          "version": 1
        },
        "sourceDatabase": "data-hub-STAGING",
        "collections": [
          "mastering-flow-mapping-json",
          "mdm-content"
        ],
        "outputFormat": "json",
        "targetDatabase": "data-hub-FINAL"
      },
      "customHook": null,
      "retryLimit": 0,
      "batchSize": 0,
      "threadCount": 0
    },
    "3": {
      "name": "json-mastering-step-json",
      "description": "matches and merges the docs",
      "stepDefinitionName": "default-mastering",
      "stepDefinitionType": "MASTERING",
      "options": {
        "stepUpdate": true,
        "sourceQuery": "cts.collectionQuery('mastering-flow-mapping-json')",
        "acceptsBatch": true,
        "targetEntity": "Order",
        "sourceDatabase": "data-hub-FINAL",
        "collections": [
          "mastered1"
        ],
        "mergeOptions": {
          "propertyDefs": {
            "properties": [
              {
                "namespace": "",
                "localname": "CustomerID",
                "name": "CustomerID"
              },
              {
                "namespace": "",
                "localname": "ShipAddress",
                "name": "ShipAddress"
              },
              {
                "namespace": "",
                "localname": "ShipCity",
                "name": "ShipCity"
              }
            ]
          },
          "algorithms": {
            "stdAlgorithm": {
              "timestamp": {
                "path": ""
              }
            },
            "custom": [],
            "collections": {
              "onMerge": {
                "add": {
                  "collection": [
                    "test"
                  ]
                },
                "remove": {
                  "collection": [
                    ""
                  ]
                },
                "set": {
                  "collection": [
                    ""
                  ]
                }
              },
              "onNoMatch": {
                "add": {
                  "collection": [
                    ""
                  ]
                },
                "remove": {
                  "collection": [
                    ""
                  ]
                },
                "set": {
                  "collection": [
                    ""
                  ]
                }
              },
              "onNotification": {
                "add": {
                  "collection": [
                    ""
                  ]
                },
                "remove": {
                  "collection": [
                    ""
                  ]
                },
                "set": {
                  "collection": [
                    ""
                  ]
                }
              },
              "onArchive": {
                "add": {
                  "collection": [
                    ""
                  ]
                },
                "remove": {
                  "collection": [
                    ""
                  ]
                },
                "set": {
                  "collection": [
                    ""
                  ]
                }
              }
            }
          },
          "mergeStrategies": [],
          "merging": [
            {
              "propertyName": "CustomerID",
              "sourceWeights": []
            },
            {
              "propertyName": "ShipCity",
              "sourceWeights": []
            },
            {
              "propertyName": "ShipAddress",
              "sourceWeights": []
            }
          ]
        },
        "matchOptions": {
          "dataFormat": "json",
          "propertyDefs": {
            "property": [
              {
                "localname": "CustomerID",
                "name": "CustomerID"
              },
              {
                "localname": "ShipCity",
                "name": "ShipCity"
              },
              {
                "localname": "ShipAddress",
                "name": "ShipAddress"
              }
            ]
          },
          "algorithms": {
            "algorithm": [
            ]
          },
          "collections": {
            "content": []
          },
          "scoring": {
            "add": [
              {
                "propertyName": "CustomerID",
                "weight": "10"
              },
              {
                "propertyName": "ShipCity",
                "weight": "5"
              },
              {
                "propertyName": "ShipAddress",
                "weight": "20"
              }
            ],
            "expand": [],
            "reduce": []
          },
          "actions": {
            "action": []
          },
          "thresholds": {
            "threshold": [
              {
                "above": "14",
                "label": "Likely Match",
                "action": "notify"
              },
              {
                "above": "24",
                "label": "Definitive Match",
                "action": "merge"
              }
            ]
          },
          "tuning": {
            "maxScan": 200
          }
        },
        "targetDatabase": "data-hub-FINAL"
      },
      "customHook": null,
      "retryLimit": 0,
      "batchSize": 100,
      "threadCount": 4
    }
  }
}

=== Marklogic-retired/marklogic-data-hub/marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flows/run/test-data/flows/CustomerByValue.flow.json
{
  "name": "CustomerByValue",
  "options": {
    "collections": [
      "CustomerByValue"
    ],
    "targetEntity": "Customer",
    "sourceQuery": "cts.values(cts.uriReference())",
    "sourceQueryIsScript": true,
    "writeStepOutput": false
  },
  "description": "flow description",
  "steps": {
    "1": {
      "stepDefinitionName": "CustomerByValue",
      "stepDefinitionType": "CUSTOM",
      "options": {
        "sourceDatabase": "data-hub-FINAL",
        "targetDatabase": "data-hub-FINAL"
      }
    }
  }
}

=== Marklogic-retired/marklogic-data-hub/examples/dh-5-example/flows/ingestion_only-flow.flow.json
{
  "name": "ingestion_only-flow",
  "description": "This is the default flow containing all of the default steps",
  "batchSize": 100,
  "threadCount": 4,
  "options": {
    "sourceQuery": null
  },
  "steps": {
    "1": {
      "name": "json-ingest-step-json",
      "description": "ingests json docs in JSON format to data-hub-STAGING",
      "stepDefinitionName": "default-ingestion",
      "stepDefinitionType": "INGESTION",
      "options": {
        "sourceQuery": null,
        "collections": [
          "json-ingest-step-json"
        ],
        "permissions": "rest-reader,read,rest-writer,update",
        "outputFormat": "json",
        "targetDatabase": "data-hub-STAGING"
      },
      "customHook": {},
      "retryLimit": 0,
      "batchSize": 100,
      "threadCount": 4,
      "fileLocations": {
        "inputFilePath": "input",
        "inputFileType": "json",
        "outputURIReplacement": ".*input*.,'/ingestion-flow/json/'"
      }
    },
    "2": {
      "name": "xml-ingest-step-xml",
      "description": "ingests xml docs in XML formart to data-hub-STAGING",
      "stepDefinitionName": "default-ingestion",
      "stepDefinitionType": "INGESTION",
      "options": {
        "sourceQuery": null,
        "collections": [
          "xml-ingest-step-xml"
        ],
        "permissions": "rest-reader,read,rest-writer,update",
        "outputFormat": "xml",
        "targetDatabase": "data-hub-STAGING"
      },
      "customHook": {},
      "retryLimit": 0,
      "batchSize": 100,
      "threadCount": 4,
      "fileLocations": {
        "inputFilePath": "input",
        "inputFileType": "xml",
        "outputURIReplacement": ".*input*.,'/ingestion-flow/xml/'"
      }
    },
    "3": {
      "name": "csv-ingest-step-json",
      "description": "ingests csv file in JSON formart to data-hub-STAGING",
      "stepDefinitionName": "default-ingestion",
      "stepDefinitionType": "INGESTION",
      "options": {
        "sourceQuery": null,
        "collections": [
          "csv-ingest-step-json"
        ],
        "permissions": "rest-reader,read,rest-writer,update",
        "outputFormat": "json",
        "targetDatabase": "data-hub-STAGING"
      },
      "customHook": {},
      "retryLimit": 0,
      "batchSize": 100,
      "threadCount": 4,
      "fileLocations": {
        "inputFilePath": "input",
        "inputFileType": "csv",
        "outputURIReplacement": ".*input*.,'/ingestion-flow/csv/json/'"
      }
    },
    "4": {
      "name": "csv-ingest-step-xml",
      "description": "ingests csv docs in XML formart to data-hub-STAGING",
      "stepDefinitionName": "default-ingestion",
      "stepDefinitionType": "INGESTION",
      "options": {
        "sourceQuery": null,
        "collections": [
          "csv-ingest-step-xml"
        ],
        "permissions": "rest-reader,read,rest-writer,update",
        "outputFormat": "xml",
        "targetDatabase": "data-hub-STAGING"
      },
      "customHook": {},
      "retryLimit": 0,
      "batchSize": 100,
      "threadCount": 4,
      "fileLocations": {
        "inputFilePath": "input",
        "inputFileType": "csv",
        "outputURIReplacement": ".*input*.,'/ingestion-flow/csv/xml/'"
      }
    },
    "5" : {
      "name" : "ingest-binary",
      "description" : "ingests binary docs into data-hub-STAGING",
      "options" : {
        "sourceQuery" : null,
        "collections" : [ "ingest-binary" ],
        "outputFormat" : "json",
        "targetDatabase" : "data-hub-STAGING"
      },
      "customHook" : { },
      "retryLimit" : 0,
      "batchSize" : 0,
      "threadCount" : 0,
      "stepDefinitionName" : "default-ingestion",
      "stepDefinitionType" : "INGESTION",
      "fileLocations" : {
        "inputFilePath" : "input",
        "outputURIReplacement" : ".*input*.,'/ingestion-flow/binary/'",
        "inputFileType" : "binary"
      }
    }, 
    "6" : {
      "name" : "json-ingest-step-text",
      "description" : "ingests json docs into data-hub-STAGING in text format",
      "options" : {
        "sourceQuery" : null,
        "collections" : [ "json-ingest-step-text" ],
        "outputFormat" : "text",
        "targetDatabase" : "data-hub-STAGING"
      },
      "customHook" : { },
      "retryLimit" : 0,
      "batchSize" : 0,
      "threadCount" : 0,
      "stepDefinitionName" : "default-ingestion",
      "stepDefinitionType" : "INGESTION",
      "fileLocations" : {
        "inputFilePath" : "input",
        "outputURIReplacement" : ".*input*.,'/ingestion-flow/json/txt/'",
        "inputFileType" : "json"
      }
    },
    "7" : {
      "name" : "xml-ingest-step-text",
      "description" : "ingests binary docs into data-hub-STAGING",
      "options" : {
        "sourceQuery" : null,
        "collections" : [ "xml-ingest-step-text" ],
        "outputFormat" : "text",
        "targetDatabase" : "data-hub-STAGING"
      },
      "customHook" : { },
      "retryLimit" : 0,
      "batchSize" : 0,
      "threadCount" : 0,
      "stepDefinitionName" : "default-ingestion",
      "stepDefinitionType" : "INGESTION",
      "fileLocations" : {
        "inputFilePath" : "input",
        "outputURIReplacement" : ".*input*.,'/ingestion-flow/xml/txt/'",
        "inputFileType" : "xml"
      }
    }
  }
}

=== Marklogic-retired/marklogic-data-hub/examples/dh-5-example/flows/ingestion_mapping-flow.flow.json
{
  "name" : "ingestion_mapping-flow",
  "description" : "This is the default flow containing all of the default steps",
  "batchSize" : 100,
  "threadCount" : 4,
  "stopOnError" : false,
  "options" : {
    "sourceQuery" : null
  },
  "version" : 0,
  "steps" : {
    "1" : {
      "name" : "ingest-step-json",
      "description" : "ingests json docs in JSON format to data-hub-STAGING",
      "options" : {
        "sourceQuery" : null,
        "collections" : [ "mapping-flow-ingestion-json" ],
        "permissions" : "rest-reader,read,rest-writer,update",
        "outputFormat" : "json",
        "targetDatabase" : "data-hub-FINAL"
      },
      "customHook" : { },
      "batchSize" : 100,
      "threadCount" : 4,
      "stepDefinitionName" : "default-ingestion",
      "stepDefinitionType" : "INGESTION",
      "fileLocations" : {
        "inputFilePath" : "input",
        "inputFileType" : "json",
        "outputURIReplacement" : ".*input*.,'/mapping-flow/json/'"
      }
    },
    "2" : {
      "name" : "mapping-step-json",
      "description" : "maps and harmonizes JSON docs to data-hub-FINAL",
      "options" : {
        "sourceQuery" : "cts.collectionQuery('mapping-flow-ingestion-json')",
        "mapping" : {
          "name" : "OrderMappingJson",
          "version" : 1
        },
        "sourceDatabase" : "data-hub-FINAL",
        "collections" : [ "mapping-flow-mapping-json" ],
        "outputFormat" : "json",
        "targetDatabase" : "data-hub-FINAL"
      },
      "customHook" : null,
      "batchSize" : 0,
      "threadCount" : 0,
      "stepDefinitionName" : "entity-services-mapping",
      "stepDefinitionType" : "MAPPING"
    },
    "3" : {
      "name" : "ingest-step-xml",
      "description" : "ingests xml docs in XML format to data-hub-STAGING",
      "options" : {
        "sourceQuery" : null,
        "collections" : [ "mapping-flow-ingestion-xml" ],
        "permissions" : "rest-reader,read,rest-writer,update",
        "outputFormat" : "xml",
        "targetDatabase" : "data-hub-STAGING"
      },
      "customHook" : { },
      "batchSize" : 100,
      "threadCount" : 4,
      "stepDefinitionName" : "default-ingestion",
      "stepDefinitionType" : "INGESTION",
      "fileLocations" : {
        "inputFilePath" : "input",
        "inputFileType" : "xml",
        "outputURIReplacement" : ".*input*.,'/mapping-flow/xml/'"
      }
    },
    "4" : {
      "name" : "mapping-step-xml",
      "description" : "maps and harmonizes XML docs to data-hub-FINAL",
      "options" : {
        "sourceQuery" : "cts.collectionQuery('mapping-flow-ingestion-xml')",
        "mapping" : {
          "name" : "OrderMappingXml",
          "version" : 1
        },
        "sourceDatabase" : "data-hub-STAGING",
        "collections" : [ "mapping-flow-mapping-xml" ],
        "outputFormat" : "xml",
        "targetDatabase" : "data-hub-FINAL"
      },
      "customHook" : null,
      "batchSize" : 0,
      "threadCount" : 0,
      "stepDefinitionName" : "entity-services-mapping",
      "stepDefinitionType" : "MAPPING"
    }
  }
}
